### ISSUE TITLE
bmob云

### ISSUE THREAD

**Issue by Drunk7** [LeeLulin/ToDoList#3]
你好，我想问一下bmob后端怎么设计的？

**Comment by AngryFishes** [comment]
我也想问，能给看看嘛，或者留个联系方式

**Comment by Drunk7** [comment]
如果您收到了，能发给我一份吗？感谢！！！


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"AngryFishes"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月3日(星期五) 下午3:42
收件人:&nbsp;"LeeLulin/ToDoList"<ToDoList@noreply.github.com&gt;;
抄送:&nbsp;"Drunk"<1742105034@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [LeeLulin/ToDoList] bmob云 (#3)





 
我也想问，能给看看嘛，或者留个联系方式

**Comment by LeeLulin** [comment]
> 你好，我想问一下bmob后端怎么设计的？

您好，Bmob云数据库结构已经更新到README.MD，本项目停止维护，请自行更换自己的appID
