### ISSUE TITLE
Could not resolve cn.bmob.android:bmob-sdk:3.7.8

### ISSUE THREAD

**Issue by 6Zeat** [LeeLulin/ToDoList#6]
你好，我下载之后运行，一直报错Could not resolve cn.bmob.android:bmob-sdk:3.7.8，请问该如何解决呢？

**Comment by blackmail3** [comment]
请问解决问题了吗

**Comment by LeeLulin** [comment]
[SDK导入](http://doc.bmob.cn/data/android/index.html#sdk_1)

implementation 'io.github.bmob:android-sdk:3.8.13'

**Comment by LeeLulin** [comment]
> 你好，我下载之后运行，一直报错Could not resolve cn.bmob.android:bmob-sdk:3.7.8，请问该如何解决呢？

貌似是bmob云版本的问题，去官网查一下最新版本
