### ISSUE TITLE
怎样运行项目 要求什么环境

### ISSUE THREAD

**Issue by DayoWong0** [LeeLulin/ToDoList#7]
用Android Studio打开后，缺少BuildConfig 
![image](https://user-images.githubusercontent.com/23241655/163820499-9a832b0f-301f-4914-8e78-345f25267bd7.png)

bmob包也没有导入

**Comment by LeeLulin** [comment]
> 用Android Studio打开后，缺少BuildConfig ![image](https://user-images.githubusercontent.com/23241655/163820499-9a832b0f-301f-4914-8e78-345f25267bd7.png)
> 
> bmob包也没有导入

1. 缺少BuildConfig重新build一下
![屏幕快照 2022-04-20 下午11 39 27 上午](https://user-images.githubusercontent.com/27431274/164145714-b1d38fd6-b073-4aa7-9c10-e481a39bd46b.png)

2. 尝试去bmob云官方查找最新版本
